import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.css"
import Header from "@/header/header";
import Menu from "@/menu/menu";
import Footer from "@/footer/footer";
import "bootstrap-icons/font/bootstrap-icons.css"


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body >
      <Header />
        <Menu />
        {children}
        <Footer />
      </body>
    </html>
  );
}
